In [2]:
import polars as pl                            # Import required libraries

In [3]:
sales = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\E-Commerce-Sales-Customer-Analytics\data\raw\Sales.csv")
# Read the first dataset

In [4]:
sales.glimpse()

Rows: 62884
Columns: 9
$ Order Number  <i64> 366000, 366001, 366001, 366002, 366002, 366002, 366004, 366004, 366005, 366007
$ Line Item     <i64> 1, 1, 2, 1, 2, 3, 1, 2, 1, 1
$ Order Date    <str> '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016'
$ Delivery Date <str> null, '1/13/2016', '1/13/2016', '1/12/2016', '1/12/2016', '1/12/2016', null, null, null, null
$ CustomerKey   <i64> 265598, 1269051, 1269051, 266019, 266019, 266019, 1107461, 1107461, 844003, 2035771
$ StoreKey      <i64> 10, 0, 0, 0, 0, 0, 38, 38, 33, 43
$ ProductKey    <i64> 1304, 1048, 2007, 1106, 373, 1080, 163, 1529, 421, 1617
$ Quantity      <i64> 1, 2, 1, 7, 1, 4, 6, 2, 4, 1
$ Currency Code <str> 'CAD', 'USD', 'USD', 'CAD', 'CAD', 'CAD', 'GBP', 'GBP', 'EUR', 'USD'

In [39]:
total_null = sum(sales.null_count())[0]
total_rows = len(sales)
null_percentage = round(total_null/total_rows * 100,2)
print(f"Null percentage: {null_percentage} %")
# Only Delivery Date column has null values, which makes up approximately 80 % of total values

Null percentage: 79.06 %

In [16]:
sales.head(20)

shape: (20, 9)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬────────────┬──────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ StoreKey ┆ ProductKey ┆ Quantity ┆ Currency Code │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ---           │
│ i64          ┆ i64       ┆ str        ┆ str           ┆   ┆ i64      ┆ i64        ┆ i64      ┆ str           │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪════════════╪══════════╪═══════════════╡
│ 366000       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 10       ┆ 1304       ┆ 1        ┆ CAD           │
│ 366001       ┆ 1         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 1048       ┆ 2        ┆ USD           │
│ 366001       ┆ 2         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 2007       ┆ 1        ┆ USD           │
│ 366002       ┆ 1         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 1106       ┆ 7        ┆ CAD           │
│ 366002       ┆ 2         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 373        ┆ 1        ┆ CAD           │
│ …            ┆ …         ┆ …          ┆ …             ┆ … ┆ …        ┆ …          ┆ …        ┆ …             │
│ 366010       ┆ 1         ┆ 1/1/2016   ┆ 1/8/2016      ┆ … ┆ 0        ┆ 618        ┆ 5        ┆ CAD           │
│ 366011       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 128        ┆ 7        ┆ USD           │
│ 366011       ┆ 2         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1638       ┆ 1        ┆ USD           │
│ 366011       ┆ 3         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1634       ┆ 1        ┆ USD           │
│ 366011       ┆ 4         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 2392       ┆ 3        ┆ USD           │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴────────────┴──────────┴───────────────┘

In [43]:
sales = sales.with_columns(
    pl.col("Order Date").str.to_date("%m/%d/%Y").alias("Order_Date"),
    pl.col("Delivery Date").str.to_date("%m/%d/%Y").alias("Delivery_Date")
)
sales
# Changed the type of Order Date/Delivery Date columns from str to date

shape: (62_884, 11)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬───────────────┬────────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ Quantity ┆ Currency Code ┆ Order_Date ┆ Delivery_Date │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---           ┆ ---        ┆ ---           │
│ i64          ┆ i64       ┆ str        ┆ str           ┆   ┆ i64      ┆ str           ┆ date       ┆ date          │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪═══════════════╪════════════╪═══════════════╡
│ 366000       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 1        ┆ CAD           ┆ 2016-01-01 ┆ null          │
│ 366001       ┆ 1         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 2        ┆ USD           ┆ 2016-01-01 ┆ 2016-01-13    │
│ 366001       ┆ 2         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 1        ┆ USD           ┆ 2016-01-01 ┆ 2016-01-13    │
│ 366002       ┆ 1         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 7        ┆ CAD           ┆ 2016-01-01 ┆ 2016-01-12    │
│ 366002       ┆ 2         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 1        ┆ CAD           ┆ 2016-01-01 ┆ 2016-01-12    │
│ …            ┆ …         ┆ …          ┆ …             ┆ … ┆ …        ┆ …             ┆ …          ┆ …             │
│ 2243030      ┆ 1         ┆ 2/20/2021  ┆ null          ┆ … ┆ 3        ┆ USD           ┆ 2021-02-20 ┆ null          │
│ 2243031      ┆ 1         ┆ 2/20/2021  ┆ 2/24/2021     ┆ … ┆ 4        ┆ EUR           ┆ 2021-02-20 ┆ 2021-02-24    │
│ 2243032      ┆ 1         ┆ 2/20/2021  ┆ 2/23/2021     ┆ … ┆ 2        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
│ 2243032      ┆ 2         ┆ 2/20/2021  ┆ 2/23/2021     ┆ … ┆ 2        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
│ 2243032      ┆ 3         ┆ 2/20/2021  ┆ 2/23/2021     ┆ … ┆ 7        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴───────────────┴────────────┴───────────────┘

In [44]:
sales = sales.drop("Order Date","Delivery Date") 
# Remove unnecessary columns

In [45]:
sales = sales.rename({"CustomerKey" : "Customer Key",
                      "StoreKey" : "Store Key",
                      "ProductKey" : "Product Key",
                      "Order_Date" : "Order Date",
                      "Delivery_Date" : "Delivery Date"})

In [36]:
sales

shape: (62_884, 9)
┌──────────────┬───────────┬──────────────┬───────────┬───┬──────────┬───────────────┬────────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Customer Key ┆ Store Key ┆ … ┆ Quantity ┆ Currency Code ┆ Order Date ┆ Delivery Date │
│ ---          ┆ ---       ┆ ---          ┆ ---       ┆   ┆ ---      ┆ ---           ┆ ---        ┆ ---           │
│ i64          ┆ i64       ┆ i64          ┆ i64       ┆   ┆ i64      ┆ str           ┆ date       ┆ date          │
╞══════════════╪═══════════╪══════════════╪═══════════╪═══╪══════════╪═══════════════╪════════════╪═══════════════╡
│ 366000       ┆ 1         ┆ 265598       ┆ 10        ┆ … ┆ 1        ┆ CAD           ┆ 2016-01-01 ┆ null          │
│ 366001       ┆ 1         ┆ 1269051      ┆ 0         ┆ … ┆ 2        ┆ USD           ┆ 2016-01-01 ┆ 2016-01-13    │
│ 366001       ┆ 2         ┆ 1269051      ┆ 0         ┆ … ┆ 1        ┆ USD           ┆ 2016-01-01 ┆ 2016-01-13    │
│ 366002       ┆ 1         ┆ 266019       ┆ 0         ┆ … ┆ 7        ┆ CAD           ┆ 2016-01-01 ┆ 2016-01-12    │
│ 366002       ┆ 2         ┆ 266019       ┆ 0         ┆ … ┆ 1        ┆ CAD           ┆ 2016-01-01 ┆ 2016-01-12    │
│ …            ┆ …         ┆ …            ┆ …         ┆ … ┆ …        ┆ …             ┆ …          ┆ …             │
│ 2243030      ┆ 1         ┆ 1216913      ┆ 43        ┆ … ┆ 3        ┆ USD           ┆ 2021-02-20 ┆ null          │
│ 2243031      ┆ 1         ┆ 511229       ┆ 0         ┆ … ┆ 4        ┆ EUR           ┆ 2021-02-20 ┆ 2021-02-24    │
│ 2243032      ┆ 1         ┆ 331277       ┆ 0         ┆ … ┆ 2        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
│ 2243032      ┆ 2         ┆ 331277       ┆ 0         ┆ … ┆ 2        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
│ 2243032      ┆ 3         ┆ 331277       ┆ 0         ┆ … ┆ 7        ┆ CAD           ┆ 2021-02-20 ┆ 2021-02-23    │
└──────────────┴───────────┴──────────────┴───────────┴───┴──────────┴───────────────┴────────────┴───────────────┘

In [88]:
stores = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\E-Commerce-Sales-Customer-Analytics\data\raw\Stores.csv")
stores

shape: (67, 5)
┌──────────┬───────────────┬──────────────────────────────┬───────────────┬───────────┐
│ StoreKey ┆ Country       ┆ State                        ┆ Square Meters ┆ Open Date │
│ ---      ┆ ---           ┆ ---                          ┆ ---           ┆ ---       │
│ i64      ┆ str           ┆ str                          ┆ i64           ┆ str       │
╞══════════╪═══════════════╪══════════════════════════════╪═══════════════╪═══════════╡
│ 1        ┆ Australia     ┆ Australian Capital Territory ┆ 595           ┆ 1/1/2008  │
│ 2        ┆ Australia     ┆ Northern Territory           ┆ 665           ┆ 1/12/2008 │
│ 3        ┆ Australia     ┆ South Australia              ┆ 2000          ┆ 1/7/2012  │
│ 4        ┆ Australia     ┆ Tasmania                     ┆ 2000          ┆ 1/1/2010  │
│ 5        ┆ Australia     ┆ Victoria                     ┆ 2000          ┆ 12/9/2015 │
│ …        ┆ …             ┆ …                            ┆ …             ┆ …         │
│ 63       ┆ United States ┆ Utah                         ┆ 2000          ┆ 3/6/2008  │
│ 64       ┆ United States ┆ Washington DC                ┆ 1330          ┆ 1/1/2010  │
│ 65       ┆ United States ┆ West Virginia                ┆ 1785          ┆ 1/1/2012  │
│ 66       ┆ United States ┆ Wyoming                      ┆ 840           ┆ 1/1/2014  │
│ 0        ┆ Online        ┆ Online                       ┆ null          ┆ 1/1/2010  │
└──────────┴───────────────┴──────────────────────────────┴───────────────┴───────────┘

In [87]:
stores.glimpse()

Rows: 67
Columns: 5
$ StoreKey      <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ Country       <str> 'Australia', 'Australia', 'Australia', 'Australia', 'Australia', 'Australia', 'Canada', 'Canada', 'Canada', 'Canada'
$ State         <str> 'Australian Capital Territory', 'Northern Territory', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia', 'New Brunswick', 'Newfoundland and Labrador', 'Northwest Territories', 'Nunavut'
$ Square Meters <i64> 595, 665, 2000, 2000, 2000, 2000, 1105, 2105, 1500, 1210
$ Open Date     <str> '1/1/2008', '1/12/2008', '1/7/2012', '1/1/2010', '12/9/2015', '1/1/2010', '5/7/2007', '7/2/2014', '3/4/2005', '4/4/2015'

In [52]:
stores.null_count()

shape: (1, 5)
┌──────────┬─────────┬───────┬───────────────┬───────────┐
│ StoreKey ┆ Country ┆ State ┆ Square Meters ┆ Open Date │
│ ---      ┆ ---     ┆ ---   ┆ ---           ┆ ---       │
│ u32      ┆ u32     ┆ u32   ┆ u32           ┆ u32       │
╞══════════╪═════════╪═══════╪═══════════════╪═══════════╡
│ 0        ┆ 0       ┆ 0     ┆ 1             ┆ 0         │
└──────────┴─────────┴───────┴───────────────┴───────────┘

In [90]:
stores = stores.with_columns(
    pl.col("Open Date").str.to_date("%m/%d/%Y").alias("Open_Date")
)

In [97]:
stores = stores.drop("Open Date")

In [100]:
stores.rename({"Open_Date" : "Open Date","StoreKey" : "Store Key"})

shape: (67, 5)
┌───────────┬───────────────┬──────────────────────────────┬───────────────┬────────────┐
│ Store Key ┆ Country       ┆ State                        ┆ Square Meters ┆ Open Date  │
│ ---       ┆ ---           ┆ ---                          ┆ ---           ┆ ---        │
│ i64       ┆ str           ┆ str                          ┆ i64           ┆ date       │
╞═══════════╪═══════════════╪══════════════════════════════╪═══════════════╪════════════╡
│ 1         ┆ Australia     ┆ Australian Capital Territory ┆ 595           ┆ 2008-01-01 │
│ 2         ┆ Australia     ┆ Northern Territory           ┆ 665           ┆ 2008-01-12 │
│ 3         ┆ Australia     ┆ South Australia              ┆ 2000          ┆ 2012-01-07 │
│ 4         ┆ Australia     ┆ Tasmania                     ┆ 2000          ┆ 2010-01-01 │
│ 5         ┆ Australia     ┆ Victoria                     ┆ 2000          ┆ 2015-12-09 │
│ …         ┆ …             ┆ …                            ┆ …             ┆ …          │
│ 63        ┆ United States ┆ Utah                         ┆ 2000          ┆ 2008-03-06 │
│ 64        ┆ United States ┆ Washington DC                ┆ 1330          ┆ 2010-01-01 │
│ 65        ┆ United States ┆ West Virginia                ┆ 1785          ┆ 2012-01-01 │
│ 66        ┆ United States ┆ Wyoming                      ┆ 840           ┆ 2014-01-01 │
│ 0         ┆ Online        ┆ Online                       ┆ null          ┆ 2010-01-01 │
└───────────┴───────────────┴──────────────────────────────┴───────────────┴────────────┘

In [56]:
stores.filter(
    pl.col("StoreKey") == 0
)

shape: (1, 5)
┌──────────┬─────────┬────────┬───────────────┬───────────┐
│ StoreKey ┆ Country ┆ State  ┆ Square Meters ┆ Open Date │
│ ---      ┆ ---     ┆ ---    ┆ ---           ┆ ---       │
│ i64      ┆ str     ┆ str    ┆ i64           ┆ str       │
╞══════════╪═════════╪════════╪═══════════════╪═══════════╡
│ 0        ┆ Online  ┆ Online ┆ null          ┆ 1/1/2010  │
└──────────┴─────────┴────────┴───────────────┴───────────┘